---
  - name: change config when condition occures
    gather_facts: no
    connection: network_cli
    hosts: "ios-device"

    tasks:
      - name: show hostname
        ios_command:
          commands:
            - show run | s ospf
        register: output

      - name: config example
        when: '"id" in "{{output.stdout}}"'
        ios_config:
          lines:
            - logging buffered 30000