---
r1:
    hostname: '172.16.1.1'
    port: 22
    username: 'maciej'
    password: '6565'
    platform: 'cisco_ios'

iosv-2:
    hostname: '172.16.2.1'
    port: 22
    username: 'maciej'
    password: '6565'
    platform: 'cisco_ios'