#configure snmp contact
---
  - name: Configure SNMP Contact
    hosts: "router_by_name"
    gather_facts: false
    connection: local

    vars:
      cli:
        host: "{{ ansible_host }}"
        port: 22
        username: "{{ username }}"
        password: "{{ password }}"
        transport: cli
        

    tasks:

      - name: configure snmp contact
        community.network.ce_snmp_contact:          
          contact: maciej_test
          #provider: "{{ cli }}"
          state: present
                    
      - name: show output
        debug:
          var: output