#configure snmp contact
# deosnt work :(
---
  - name: Configure SNMP Contact
    hosts: all
    gather_facts: false
    connection: local        

    tasks:
      - name: configure snmp contact
        community.network.ce_snmp_contact:          
          contact: maciej_test
          state: present
          provider: cli
                    
      - name: show output
        debug:
          var: output
